version: '3.8'
services:
#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.frontend
#    ports:
#      - "8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5200:80"