version: '3.8'
services:

  frontend:
    image: quizzweb
    container_name: qw
    build: ./frontend
    ports:
      - "8080:80"

#  cms:
#    image: quizzcms
#    container_name: qc
#    build: ./CMS
#    ports:
#      - "5000:80"