version: '3.8'

networks:
  net:
    driver: bridge

services:

  frontend:
    image: quizzweb
    container_name: qw
    build: ./frontend
    ports:
      - "8080:8080"

  cms:
    image: quizzcms
    container_name: qc
    build: ./CMS
    ports:
      - "5000:80"

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 2
    networks:
      - net

  api:
    container_name: quizzapi
    build: ./backend/QuizzWebApi/.
    ports:
      - "5200:80"
    environment:
      Connection_Strings_DefaultConnection: "Host=db; Port=5432; Database=postgres; Username=postgres; Password=postgres"
    volumes:
      - static-files:/app/static/images
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

  email:
    container_name: email
    build: ./backend/EmailService/.
    ports:
      - "5120:80"
    networks:
      - net
  
  api.seq:
    image: datalust/seq:latest
    container_name: api-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    networks:
      - net

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - "15672:15672"
    networks:
      - net

volumes:
  pgdata: {}
  static-files: {}
