version: '3.8'
services:
#  frontend:
#    build:
#      context: .
#      dockerfile: Dockerfile.frontend
#    ports:
#      - "8080:80"

  api:
    image: quizzapi
    container_name: qa
    build: ./backend
    ports:
      - "5200:80"